name: Deployment
on: [push, workflow_dispatch]
jobs:
  test:
    # needs: lint
    name: Test
    env:
      PORT: 8080
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./backend/requirements.txt
      - name: Lint with Ruff
        uses: chartboost/ruff-action@v1
        with:
          src: "./backend/app/"
      - name: Run pytest
        run: cd backend && pytest
      - name: Print Env Variables
        run: echo "${{env.PORT}}"
  # deploy:
  #   needs: test
  #   runs-on: ubuntu-latest
