name: Deployment
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip" # caching pip dependencies
      - run: pip3 install -r ./backend/requirements.txt
      - name: Run tests
        run: cd backend && pytest
  # deploy:
  #   needs: test
  #   runs-on: ubuntu-latest
