name: Deployment
on: [push, workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          path: "./backend/app/"
          plugins: "flake8-bugbear==22.1.11 flake8-black"
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip" # caching pip dependencies
      - run: pip3 install -r ./backend/requirements.txt
      - name: Run tests
        run: cd backend && pytest
  # deploy:
  #   needs: test
  #   runs-on: ubuntu-latest
